spring:
  application.name: eureka-server
server:
  port: 1001

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

enableSelfPreservation: false